git clone git://github.com/fosscord/css-mediaquery.git css-mediaquery
git clone git://github.com/fosscord/docker.git docker
git clone git://github.com/fosscord/fosscord.git fosscord
git clone git://github.com/fosscord/fosscord-server.git server
git clone git://github.com/fosscord/fosscord-client.git client
git clone git://github.com/fosscord/fosscord-client-native.git client-native
git clone git://github.com/fosscord/fosscord-docs.git docs
git clone git://github.com/fosscord/fosscord-landingpage.git landingpage
git clone git://github.com/fosscord/fosscord-plugins.git plugins
git clone git://github.com/fosscord/fosscord-themes.git themes
git clone git://github.com/fosscord/fosscord-ui.git ui
git clone git://github.com/fosscord/fosscord.js.git fosscord.js
git clone git://github.com/fosscord/react-native-withcss.git react-native-withcss
