git clone https://github.com/fosscord/css-mediaquery.git css-mediaquery
git clone https://github.com/fosscord/docker.git docker
git clone https://github.com/fosscord/fosscord.git fosscord
git clone https://github.com/fosscord/fosscord-client.git client
git clone https://github.com/fosscord/fosscord-client-native.git client-native
git clone https://github.com/fosscord/fosscord-docs.git docs
git clone https://github.com/fosscord/fosscord-landingpage.git landingpage
git clone https://github.com/fosscord/fosscord-plugins.git plugins
git clone https://github.com/fosscord/fosscord-server.git server
git clone https://github.com/fosscord/fosscord-themes.git themes
git clone https://github.com/fosscord/fosscord-ui.git ui
git clone https://github.com/fosscord/fosscord-voice-gateway.git voice-gateway
git clone https://github.com/fosscord/fosscord.js.git fosscord.js
git clone https://github.com/fosscord/fosscord.js-builders.git fosscord.js-builders
git clone https://github.com/fosscord/fosscord.py.git fosscord.py
git clone https://github.com/fosscord/react-native-withcss.git react-native-withcss
